// Meta Data
export const metadata = {
    title: "About Us - Web Design Hub",
    description: "Generated by Web Design Hub",
}

export default function RootLayout({ children }) {
    return (children);
}