// Import Css
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

// Meta Data
export const metadata = {
    title: "LP 1 - Web Design Hub",
    description: "Generated by Web Design Hub",
}

export default function RootLayout({ children }) {
    return (children);
}