// Meta Data
export const metadata = {
    // Title & Descriptions
    title: "Pricing & Packages - Web Developers Hub",
    description: "Generated by Web Developers Hub",
    // Google Varification
    verification: {
        google: 'ziIYRBahP4WcKcps6RWRDJvZ9A00pSoI39ByXDN14us',
        other: {
            "facebook-domain-verification": ['rfth5fqyv2is1cegfmcloebw46z7nz'],
        },
    },
    // Canonical
    alternates: {
        canonical: 'https://www.webdevelopershub.co/pricing',
    },
    // OG Metas
    openGraph: {
        title: 'Pricing & Packages - Web Developers Hub',
        description: 'Generated by Web Developers Hub',
        url: 'https://www.webdevelopershub.co/pricing',
        siteName: 'Web Developers Hub',
        locale: 'en_US',
        type: 'website',
    },
}

export default function RootLayout({ children }) {
    return (children);
}