// Meta Data
export const metadata = {
    // Title & Descriptions
    title: "Creative Copy Writing - Web Design Hub",
    description: "Generated by Web Design Hub",
    // Google Varification
    verification: {
        google: 'ziIYRBahP4WcKcps6RWRDJvZ9A00pSoI39ByXDN14us',
    },
    // Canonical
    alternates: {
        canonical: 'https://www.webdesignhub.co/creative-copywriting',
    },
    // OG Metas
    openGraph: {
        title: 'Creative Copy Writing - Web Design Hub',
        description: 'Generated by Web Design Hub',
        url: 'https://www.webdesignhub.co/creative-copywriting',
        siteName: 'Web Design Hub',
        locale: 'en_US',
        type: 'website',
    },
}

export default function RootLayout({ children }) {
    return (children);
}