"use client"
// Import Fonts
import { megatFont, primary } from "./configs/fonts";
// Import Css
import "./global.css";
export const metadata = {
  title: "Design Development Web",
  description: "Generated by Design Development Web",
}
// Import Components
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${primary.className} ${megatFont.variable}`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}