// Import Fonts
import { megatFont, primary } from "./configs/fonts";
import Script from 'next/script';

// Import Css
import "./global.css";

// Meta Data
export const metadata = {
    // Title & Descriptions
    title: "Home - Web Design Hub",
    description: "Generated by Web Design Hub",
    // Google Varification
    verification: {
        google: 'ziIYRBahP4WcKcps6RWRDJvZ9A00pSoI39ByXDN14us',
    },
    // Canonical
    alternates: {
        canonical: 'https://www.webdesignhub.co',
    },
    // OG Metas
    openGraph: {
        title: 'Home - Web Design Hub',
        description: 'Generated by Web Design Hub',
        url: 'https://www.webdesignhub.co',
        siteName: 'Web Design Hub',
        locale: 'en_US',
        type: 'website',
    },
}

export default function RootLayout({ children }) {
    const GTM_ID = 'GTM-5G927FVV';
    return (
        <html lang="en">
            <Script id="google-tag-manager" strategy="lazyOnload">
                {`
                    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                    })(window,document,'script','dataLayer','${GTM_ID}');
                `}
            </Script>
            <Script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=f8df8f7a-97b8-4ca4-bbeb-c5d6ea51968e" strategy="lazyOnload">
            </Script>
            <body className={`${primary.className} ${megatFont.variable}`}>
                <noscript>
                    <iframe src={`https://www.googletagmanager.com/ns.html?id='${GTM_ID}'`} className="hidden"></iframe>
                </noscript>
                {children}
            </body>
        </html >
    );
}