// Import Fonts
import { megatFont, primary } from "./configs/fonts";
// Import Css
import "./global.css";

// Meta Data
export const metadata = {
    title: "Home - Web Design Hub",
    description: "Generated by Web Design Hub",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${primary.className} ${megatFont.variable}`}>
                {children}
            </body>
        </html>
    );
}