// Import Fonts
import Footer from "@/components/footer/Footer";
import { megatFont, poppins } from "./configs/fonts";
// Import Css
import "./global.css";
export const metadata = {
  title: "Design Development Web",
  description: "Generated by Design Development Web",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${megatFont.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}