// Import Css
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

// Meta Data
export const metadata = {
    // Title & Descriptions
    title: "Top Website Design Develop - Web Design Hub",
    description: "Generated by Web Design Hub",
    // Google Varification
    verification: {
        google: 'ziIYRBahP4WcKcps6RWRDJvZ9A00pSoI39ByXDN14us',
        other: {
            "facebook-domain-verification": ['rfth5fqyv2is1cegfmcloebw46z7nz'],
        },
    },
    // Canonical
    alternates: {
        canonical: 'https://www.webdesignhub.co/website-design-develop-usa-landing',
    },
    // OG Metas
    openGraph: {
        title: 'Top Website Design Develop - Web Design Hub',
        description: 'Generated by Web Design Hub',
        url: 'https://www.webdesignhub.co/website-design-develop-usa-landing',
        siteName: 'Web Design Hub',
        locale: 'en_US',
        type: 'website',
    },
}

export default function RootLayout({ children }) {
    return (children);
}