// Meta Data
export const metadata = {
    // Title & Descriptions
    title: "Illustration Design - Web Design Hub",
    description: "Generated by Web Design Hub",
    // Google Varification
    verification: {
        google: 'ziIYRBahP4WcKcps6RWRDJvZ9A00pSoI39ByXDN14us',
    },
    // Canonical
    alternates: {
        canonical: 'https://webdesignhub.co/illustration-design',
    },
    // OG Metas
    openGraph: {
        title: 'Illustration Design - Web Design Hub',
        description: 'Generated by Web Design Hub',
        url: 'https://webdesignhub.co/illustration-design',
        siteName: 'Web Design Hub',
        locale: 'en_US',
        type: 'website',
    },
}

export default function RootLayout({ children }) {
    return (children);
}